#!/bin/sh
set -eu

BROOT="${2:-/}"
ROOT="${1:-$PWD/broot}"

src="$BROOT/etc/portage"
dst="$ROOT/etc/portage"
if [ ! -d "$dst/.git" ]; then
    mkdir -p "$dst"  # Make sure the parent directories exist
    rm -r "$dst"
    git clone --depth=1 --recursive "file://$src" "$dst"
    git -C "$dst" remote set-url origin https://github.com/mid-kid/gentoo-config
    git -C "$dst" gc --aggressive --prune=now
else
    git -C "$dst" checkout -- .
    git -C "$dst" pull "file://$src" -q
fi

cat >> "$dst/make.conf/aa-hardware" << 'EOF'

# Modifications for live system
VIDEO_CARDS="amdgpu fbdev intel nouveau radeon radeonsi vesa"  # arch/amd64/make.defaults
CPU_FLAGS_X86="mmx mmxext sse sse2"  # arch/amd64/make.defaults
VIDEO_CARDS="$VIDEO_CARDS vmware"  # Make things pretty in virtualbox
INPUT_DEVICES="$INPUT_DEVICES wacom"  # Installing xf86-input-wacom for stylus screens
EOF

cat >> "$dst/make.conf/main" << 'EOF'

# Modifications for live system
CFLAGS="-Os -pipe $FLAGS_OPTIM_LTO $FLAGS_OPTIM_PARALLEL $FLAGS_OPTIM_MORE"
CXXFLAGS="$CFLAGS"
FFLAGS="$CFLAGS"
FCFLAGS="$CFLAGS"
RUSTFLAGS="-Copt-level=s -Clinker-plugin-lto -Clinker=clang -Clink-arg=-fuse-ld=lld"
USE="$USE bindist"
EOF

cat >> "$dst/env/clang" << 'EOF'

# Modifications for live system
CFLAGS="-pipe -Os -flto=thin"
CXXFLAGS="$CFLAGS"
EOF

cat >> "$dst/env/sys-kernel/gentoo-kernel" << 'EOF'

# Modifications for live system
NOLOCALMODCONFIG=y
EOF

cat >> "$dst/env/sys-kernel/linux-firmware" << 'EOF'

# Modifications for live system
NOLOCALFIRMCONFIG=y
EOF

cat >> "$dst/package.use/hardware" << 'EOF'

# Modifications for live system
sys-kernel/linux-firmware -initramfs
sys-boot/grub GRUB_PLATFORMS: efi-64 pc
EOF

cat >> "$dst/package.use/unnecessary" << 'EOF'

# Modifications for live system
sys-boot/grub fonts themes
EOF

cat >> "$dst/package.use/wine" << 'EOF'

# Modifications for live system
x11-libs/libpciaccess ABI_X86: 32
EOF

cat >> "$dst/package.use/zz-autounmask" << 'EOF'

# Modifications for live system
media-libs/mesa xa
EOF

cat >> "$dst/package.mask/hold" << 'EOF'

# Modifications for live system
>=dev-lang/python-3.13  # Avoid installing python versions not in PYTHON_TARGETS
EOF

cat >> "$dst/package.license" << 'EOF'

# Modifications for live system
sys-firmware/intel-microcode intel-ucode
EOF

cat >> "$dst/package.env/baseflags" << 'EOF'

# Modifications for live system
# Runtime: Compilation issues in media-libs/mesa and x11-apps/mesa-progs
dev-util/glslang baseflags  # 1.3.296.0-r1 (GCC 14.2.1_p20241221)
EOF

sed -e '/\<kde-plasma\/polkit-kde-agent\>/d' \
    -i "$dst/sets/group-i3-desktop"

rm "$dst/kernel/config.d/hardware.config"  # Don't add hardware-specific settings
rm "$dst/package.use/wayland"  # Not using sway in this liveusb, so no wayland
rm "$dst/package.env/debug"  # Save a lot of space and some time compiling

# Install kernel symlink
test -h "$ROOT/etc/kernel" || rm -rf "$ROOT/etc/kernel"
ln -vsfT portage/kernel "$ROOT/etc/kernel"

# Install eix cache
test "$BROOT" != / || eix-update
install -Dm664 -o portage -g portage -v "$BROOT/var/cache/eix/portage.eix" "$ROOT/var/cache/eix/portage.eix"
