#!/bin/sh
set -eu

if [ ! -d /mnt/distfiles ]; then
    echo "This must be run in a chroot. Be careful!" >&2
    exit 1
fi

portage_logdir="${PORTAGE_LOGDIR:-/mnt/build/buildlogs}"
unset PORTAGE_LOGDIR

export FEATURES='-news -parallel-fetch -buildpkg -binpkg-logs -unmerge-logs'
export GENTOO_MIRRORS=/mnt/distfiles
export FETCHCOMMAND='bash -c "echo ${FILE}; read"'
export CONFIG_PROTECT='-* /etc/locale.gen'
export UNINSTALL_IGNORE='/etc/kernel'  # TODO: Verify that installing installkernel doesn't remove the symlink

# kernel and modules to use
kern_pkgs="
    sys-kernel/gentoo-kernel
    sys-kernel/linux-firmware
    app-emulation/virtualbox
    sys-firmware/intel-microcode
"
# things that depend on the kernel packages but aren't in @world
kern_del_pkgs="
    virtual/dist-kernel
    virtual/linux-sources
    app-emulation/virtualbox-modules
    app-containers/waydroid
"
# packages to delete
del_grps="
    @group-sway-desktop
"
del_pkgs="
    sys-apps/fwupd
    app-doc/python-docs
    dev-java/openjdk:11
    dev-java/openjdk:17
    app-containers/waydroid-images
"
del_pkgs="$del_pkgs sys-boot/plymouth-openrc-plugin"  # Unreliable
del_pkgs="$del_pkgs custom/python-validity"  # Unreliable, requires additional setup
del_pkgs="$del_pkgs media-sound/audacity"  # 2.4.2-r3 can't be rebuilt, putting off upgrade to 3.x.
del_pkgs="$del_pkgs kde-apps/krdc"  # Requires wayland, useless on livecd
del_pkgs="$del_pkgs kde-misc/kdeconnect"  # Requires wayland, useless on livecd
del_pkgs="$del_pkgs dev-libs/weston"  # Requires wayland, useless on livecd
del_pkgs="$del_pkgs net-im/neochat net-im/tokodon custom/ktailctl"  # Requires wayland, bit of a shame
del_pkgs="$del_pkgs games-fps/xonotic"  # Really big, compresses badly
del_pkgs="$del_pkgs dev-debug/valgrind"  # glibc is compiled without debug symbols anyway
# packages to install in final system
ins_pkgs="
"
# packages to install in build environment (deps for ./geniso)
bld_pkgs="
    dev-libs/libisoburn
    sys-fs/mtools
    sys-fs/squashfs-tools
    sys-kernel/dracut
"

# Remove some packages
emerge --ask=n -W $del_grps $del_pkgs $kern_pkgs $kern_del_pkgs

# Check if packages are actually going to be removed
# NOTE: No status code on exit, so the output must be examined manually
emerge -pvc $del_pkgs $kern_del_pkgs $kern_pkgs

# Download everything
emerge --ask=n -fNe @world $ins_pkgs $bld_pkgs $kern_pkgs

# Disabling USE=wayland on gtk+:3 causes everything to not link
# immodules are loaded to update the cache, causing builds to fail
# Remove them so they don't get picked up until rebuilt
rm -rf /usr/lib64/gtk-3.0/3.0.0/immodules

# Configure /etc/locale.gen to avoid building all locales
echo 'C.UTF8 UTF-8' > /etc/locale.gen

# Make sure USE flags check out before doing anything
emerge -puDU @world
emerge --ask=n -uDU @world

# Install extra packages
emerge --ask=n -n @world $ins_pkgs

# Get rid of unnecessary packages
emerge --ask=n -c

# Perform a gcc->glibc cycle (rebuild for -march flags)
EXTRA_ECONF=--disable-bootstrap emerge --ask=n -1 sys-devel/gcc
emerge --ask=n -1 sys-libs/glibc

# Rebuild everything
PORTAGE_LOGDIR="$portage_logdir" emerge --ask=n -bNe --with-bdeps=y @world

# Install the kernel and modules
PORTAGE_LOGDIR="$portage_logdir" emerge --ask=n -bNn $kern_pkgs

# Install extra utilities in the build environment
PORTAGE_LOGDIR="$portage_logdir" emerge --ask=n -bNn1 $bld_pkgs
